#!/bin/sh

APP_NAME=$1
VERSION=`git describe --tags --long`

mkdir -p ./priv/tmp

gen_version_file() {
	echo "\n%% !!!AUTOGENERATED!!!\n%% by ./update.sh script.\n\n" > ./include/version.hrl
	echo -n "-define(PROJECT_NAME, \""${APP_NAME}"\").\n" >> ./include/version.hrl
	echo -n "-ifndef(ENGINE_VERSION).\n\t-define(ENGINE_VERSION,\"" >> ./include/version.hrl
	echo -n ${VERSION} >> ./include/version.hrl
	echo -n "\").\n-endif." >> ./include/version.hrl
	echo ${VERSION} > ./priv/tmp/vers
}

if [ -f ./priv/tmp/vers ]; then
	OLDVERS=`cat ./priv/tmp/vers`
	if [ "${VERSION}" = "${OLDVERS}" ]; then
		true
	else
		( gen_version_file )
	fi
else
	( gen_version_file )
fi
